#!/bin/bash
if [ $# -ne 1 ]; then
  yellow='\033[1;33m'
  printf "\033]0;🎥 freedisc player 🎥\007"
  echo -e "🎥 ${yellow}wklej URL filmu 🎥"
  read -r;
  filmurl="${REPLY}"
else
  filmurl="$@"
fi
ID=`echo "$filmurl" | cut -d, -f2 | cut -d- -f2`
Nazwa=`echo "$filmurl" | cut -d, -f3 | sed s/-/./g | sed s/,$//g`
Tytul=`echo $Nazwa | sed 's/./\u&/;s/\(.*\)\.\([^.]*\)$/\1\n\2/;s/\./ /g;s/\n/./g'`
printf "\033]0;🎥 odtwarzam: $Tytul 🎥\007"
echo "🎥 ${yellow}Miłego seansu! 🎥"
mpv --no-ytdl --force-media-title="$Tytul" --user-agent="Mozilla/5.0 (X11; U; Linux x86_64; pl-PL) AppleWebKit/532.0 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/549.0" --referrer="http://reseton.pl/static/player/v612/jwplayer.flash.swf" "http://stream.freedisc.pl/video/$ID/$Nazwa" && printf "\033]0;🎥 $Tytul - The End 🎥\007"
echo -e "🎥 ${yellow}Podobało się? 🎥 - Przyciśnij dowolny klawisz..."
read -rsp $'' -n 1 key

