#!/bin/bash
if [ $# -lt 3 ];then
    color=$(yad --color --gtk-palette --title="Wybierz kolor" \
            --window-icon="/home/jacek/.local/share/icons/moje/inne/paint/pędzel.png")
else
    color="#$3"
fi

transpic="${1%.*}.png"
if [ -f "$transpic" ]; then
    echo "jest"
    transpic="${1%.*}-$(date '+%Y.%m.%d %H.%M.%S').png"
fi

if [ $2 == white ];then
    blackorwhite=
elif [ $2 == black ];then
    blackorwhite=-negate
else
    echo "Nie wiem co prześwietlić, Bye"
    exit
fi

dims=$(identify -format "%wx%h" "$1")

convert "$1" $blackorwhite -grayscale Rec709Luma -contrast-stretch 4%x0.5% miff:- | \
convert -size $dims xc:$color - -alpha off -compose CopyOpacity \
-composite "$transpic"

