#!/bin/bash
loop(){
fortuna(){
wcip="`fortune dowcipy`" ;
yad --icon-name "kotek"  --title "niskopoziomowe" --button="Nie, dziękuję. Wystarczy tych bzdur."!undo:1 --button="Jeszcze jeden chamski wic?"!redo:0 --question --text "$wcip" ;
rc=$?
}
fortuna
if [[ $rc = 0 ]] ; then
loop
else exit 0
fi
}
loop


