#!/bin/bash
lokalizacja=$(exiftool -c "%.6f" "$@" | grep "GPS Position" | awk '{print $4 $5 $6 $7}')
if  [[ $lokalizacja ]]; then
xdg-open https://maps.google.pl/maps?t=h\&q=$lokalizacja
else
zenity --warning --text "brak zapisanej lokalizacji w pliku $(basename "$@")."
fi
