#!/bin/bash
nazwa=$(basename -s .sbg "$@")
#mate-terminal --class=sbagen --role=sbagen --window-with-profile=sbagen --title="$nazwa" -e "padsp sbagen-bin '$@'" &
#mate-terminal --class=sbagen --role=sbagen --window-with-profile=sbagen --title="$nazwa" -x sh -c 'set AUDIODEV=pcm.jack ; sbagen-bin -r 48000 -O '$1' | sox -q -V0 -t raw -r 48k -c2 -b 16 -e signed - -t alsa gain -3 pad 0 3 : chorus 0.5 0.9 50 0.4 2 8 : reverb 60' sh "$@" &
mate-terminal --class=sbagen --role=sbagen --window-with-profile=sbagen --title="$nazwa" -x sh -c '{ sbagen-bin -r 48000 -O '$1' 2>&1 1>&3 3>&- | lolcat -p 1000 ; } 3>&1 1>&2 | jack-stdin -n sbagen "system:playback_1" "system:playback_2" 2> /dev/null' sh "$@" &


until wmctrl -lx | egrep "$nazwa" | egrep -q mate-terminal
do
 sleep .2
done

wid=$(wmctrl -lx | egrep "$nazwa" | egrep mate-terminal | awk '{print $1}')
toggle-decorations $wid
xseticon -id $wid '/home/jacek/.local/share/icons/hicolor/16x16/apps/kwiat-życia.png'
wmctrl -ir $wid -e 0,0,0,-1,-1

