#!/bin/bash
font=/home/jacek/.local/share/fonts/Cookie-Regular.ttf
textfile="$@"
output="${textfile%.*}.jpg"

fontsize=$(yad --scale --title="Wielkość czcionki" --image=insert-text \
--text="Ustaw wielkość czcionki\nIm większa czcionka, tym krótsze linie." \
--window-icon=insert-text --min-value=24 --value=32 --max-value=64)

linelenth=$((1500 / $fontsize))
fold -sw $linelenth "$textfile" | hb-view --font-file="$font" --font-size="$fontsize" --foreground="#ffffcc" --background="#00000000" --margin="20" -O png -o /tmp/suchartemp1.png

#cat "$1" | sed '1 i\\n'| convert -size 485x -font Kalam -pointsize 22 -background transparent -fill "#fffcda" caption:@- -trim +repage -bordercolor transparent -border 15  /tmp/suchartemp1.png

height=$(convert /tmp/suchartemp1.png -format "%h" info:)
height=$((height + 50))
convert /home/jacek/.local/share/images/dosuchara.png -gravity South -crop 500x$height+0+0 /tmp/suchartemp2.png
composite -compose Over /tmp/suchartemp1.png /tmp/suchartemp2.png -alpha set "$output"
rm /tmp/suchartemp1.png /tmp/suchartemp2.png

