#!/bin/bash
# tło (okno terminala):
printf '\033[8;7;105t'
until wmctrl -lx | egrep chomikuj | egrep -q mate-terminal.Mate-terminal
do sleep .1; done
wid=$(wmctrl -lx | egrep chomikuj | egrep mate-terminal.Mate-terminal | awk '{print $1}')
toggle-decorations $wid
xseticon -id $wid '/home/jacek/.local/share/icons/hicolor/32x32/apps/chomik.png'
wmctrl -ir $wid -e 0,0,0,-1,-1

# kolor tekstu (jeśli bez lolcata 😂🐈 😹 )
red='\033[1;31m'
yellow='\033[1;33m'
green='\033[1;32m'
blue='\033[1;34m'
purple='\033[1;35m'
nocolor='\033[00m'

# czy ścieżka pliku podana?
clarg="$@"
if [[ ! $clarg ]]; then
  echo "🐹 ścieżka pliku do chomikowania:" | lolcat -a


  read -r;
  filmurl="${REPLY}"
else
  filmurl="$clarg"
fi

  echo "chomikuję do: 🐹/Film/zagraniczne" | lolcat -a
#  echo -e "${green}chomikuję do:${blue} /Film/zagraniczne${purple}"
python2 /home/jacek/sources/ChomikUploader/src/main.py -l activekarma -p alhambra -u "/Film/zagraniczne" "$clarg" 2>&1 | lolcat

echo "colored by 😹 | Przyciśnij dowolny klawisz. 🐹 Goodby 👋🏼" | lolcat -a
read -rs -n 1


